### ISSUE TITLE
Add support for substitutions

### ISSUE THREAD

**Issue by dragos** [dragos/typesafe-config-eclipse#1]
Right now the grammar doesn't recognize substitutions, like

`${akka.timeout}`

**Comment by mkurz** [comment]
I have the same issue:

![untitled](https://cloud.githubusercontent.com/assets/644927/11655537/e71900a8-9dae-11e5-8c92-e30035463104.png)

**Comment by mkurz** [comment]
Would a fix for this be a lot of work?

**Comment by dragos** [comment]
Recognizing the syntax alone shouldn't be too hard (without hyperlinking, etc).

**Comment by dragos** [comment]
I just pushed another minor release. I hope it helps.

**Comment by mkurz** [comment]
@dragos Thanks - it works!
