### ISSUE TITLE
conditional substitution expressions rejected by the parser

### ISSUE THREAD

**Issue by rkrzewski** [dragos/typesafe-config-eclipse#11]
The following HOCON expression:

```
foo = ${?bar}
```

causes an error: `no viable alternative at character '?'`

**Comment by dragos** [comment]
Should be an easy one...

**Comment by mkurz** [comment]
@dragos Cool! +1

**Comment by dragos** [comment]
..not saying I'll do it right away though. Got a busy week ahead. The usual open-source fine-print applies (help is always welcome) :smile:

**Comment by dragos** [comment]
Closed via #14.
