### ISSUE TITLE
Syntax to append elements to arrays is not supported

### ISSUE THREAD

**Issue by dotta** [dragos/typesafe-config-eclipse#6]
An error `no viable alternative at character '+'` is reported if the syntax to append elements to arrays is used.

To reproduce the problem, try

```
args += "foo.Foo"
```

**Comment by mkurz** [comment]
Same issue here

**Comment by dragos** [comment]
This is an easy one, if one of you guys wants to give it a go. I won't get to it before the weekend

**Comment by mkurz** [comment]
Is there work going on for this project? Will there be new releases?

**Comment by dragos** [comment]
@mkurz There will be new releases. Right now I'm juggling with some "real" work (meaning what I get payed for). If anyone is willing to help it would speed things up. I have some work on completion that I still need to polish, but a bugfix release could happen before that.

**Comment by dragos** [comment]
Fix via 766092d

**Comment by dotta** [comment]
Thx! :wine_glass:

**Comment by mkurz** [comment]
Cool, thanks! :beers:

**Comment by dragos** [comment]
I just published v 1.0.1 at the usual update site.

**Comment by mkurz** [comment]
@dragos Any chance you could address #1?
