### ISSUE TITLE
End of line shouldn't be mandatory in a config file

### ISSUE THREAD

**Issue by dotta** [dragos/typesafe-config-eclipse#7]
Currently, an error `no viable alternative at input '<EOF>'` is reported if the config file's content doesn't end with a newline.

**Comment by mkurz** [comment]
+1

**Comment by dragos** [comment]
I had a quick look at this, but unfortunately Xtext didn't allow me to use `EOF` as an alternative for `NL`. It seems that there's some magic treatment of `EOF` as a terminal. If someone else has any ideas, I'd be happy to merge a fix.
